### ISSUE TITLE
Error when using --bins 1

### ISSUE THREAD

**Issue by ademcan** [owenjm/damidseq_pipeline#1]
Hi,
Thank you for this great tool. 
I have a question related to the --bins option. The defaults value is 75 bp and I wanted to have a singe nucleotide level resolution, thus I used the option --bins with a value of 1. However, I always get the following error:
Illegal division by zero at [...]/damidseq_pipeline line 1115.

What is the lowest value that you tried for the --bins parameter ? Do you think that 1 is overkill ?
Thank you for your help.

**Comment by owenjm** [comment]
Hi,

Thanks for the feedback.  You shouldn't be seeing a div-by-zero there (that's the Spearman's correlation function), so my apologies -- that's a bug.

To be honest I've never reduced the bin width below 75nts.  However, there's not much advantage (and a lot of disadvantage) in using a bin size of 1: you won't gain resolution in terms of GATC fragments, and you'll almost certainly reduce your signal:noise ratio.  The memory requirements will also increase quite dramatically.  If you just want to take a look at what your data looks like at a single nucleotide resolution, you can always load the BAM file directly in IGV (the count function in IGV tools with give you a pile-up at single nucleotide resolution).

Hope this helps,
Owen

**Comment by ademcan** [comment]
Hi Owen,
Thank you for your reply and the explanation about the bin width. I wanted to give a try to see the results with a bin width at 1, but what you said makes sense, I will therefore stick with the default 75bp :)
Thank you again for this great tool.
A.
