### ISSUE TITLE
paired-end reads is avaliable for this pipeline?

### ISSUE THREAD

**Issue by runningsnail2333** [owenjm/damidseq_pipeline#10]
hi, when i run this pipeline i find this message:
Warning: paired-end reads detected.  Support for paired-end reads is experimental ...
turn for your help, can this pipleline suit pair-end sequencing?

**Comment by owenjm** [comment]
Yes, it should work fine.  We don't use PE reads ourselves (at least, not currently -- this may change this year), but others are using it.  The only thing to note is that (currently, again) you will need to align the paired reads yourself -- but you've obviously already got that far to be able to see that message :)

Just let me know if you encounter any issues.

Cheers,
Owen

**Comment by owenjm** [comment]
Version 1.4.6 now fully handles paired-end reads from the fastq files.  Just use the --paired flag and it should all work automagically ...
