### ISSUE TITLE
Specify data directory from command line

### ISSUE THREAD

**Issue by niekwit** [owenjm/damidseq_pipeline#14]
Thank you for this wonderful tool!

Would it be possible to instead of running `damidseq_pipeline` from the data directory to include the data directory as a path in a command line flag?

**Comment by owenjm** [comment]
Added this functionality to v1.6: use the --datadir flag to specify the data dir.  (All processed files will be written to your current working dir.)

Thanks so much for the suggestion, and sorry for the delay in adding this!
