### ISSUE TITLE
Inline::C not found while running damidseq_pipeline

### ISSUE THREAD

**Issue by jayramr** [owenjm/damidseq_pipeline#15]
Hi, 

I'm getting below warning when i run the perl script. 

```
./damidseq_pipeline
Inline::C not found; perl fallback used instead

damidseq_pipeline v1.5.3
Copyright 2013-22, Owen Marshall

** Inline::C not found; falling back on Perl KDE implementation ...
Please use the --gatc_frag_file option to specifiy the GFF file containing all instances of the sequence GATC ...
```

The perl module is installed as below 

```
conda list | grep -i inline
perl-inline               0.83                    pl526_0    bioconda
perl-inline-c             0.78            pl526h14c3975_1    bioconda
```

Please advise.

Thanks
Jay

**Comment by owenjm** [comment]
Hi Jay,

I'm not sure why that's not working, if the module's installed.  Have you tried some test code that uses Inline::C, e.g. the hello world example [here](https://metacpan.org/dist/Inline-C/view/lib/Inline/C/Cookbook.pod)?

If the warning's annoying, you can always run with --kde_inline=0 to force use of the perl routines.  The output will be the same whether or not you have Inline::C working; the C code just speeds up the kernel density estimation routine for normalisation, so it runs a bit faster when that module is present and working.

Cheers,
Owen

**Comment by jayramr** [comment]
Hi, 

Thanks for your update.

I have to change below to make this work 

```
export CPATH=/scratch/gencore/conda3/envs/damidseq/include:$CPATH
perl -e 'use Inline C=>q{void greet(){printf("Hello, world\n");}};greet'
Hello, world
```

I'm marking this as solved.

Thanks
Jay
