### ISSUE TITLE
Some trouble with spearman part

### ISSUE THREAD

**Issue by foriin** [owenjm/damidseq_pipeline#2]
Hi! I've tried to use your script for my Dam-ID experiments, but it keeps crashing and I can't figure why (I honestly have no idea of coding in Perl, sorry).

I've copied stdout from terminal:
**\* Calculating normalisation factor ***
Now working on Lam1 ...
Use of uninitialized value $di2sum in multiplication (*) at ./owenjm-damidseq_pipeline-2e1871c/damidseq_pipeline line 1115.
Illegal division by zero at ./owenjm-damidseq_pipeline-2e1871c/damidseq_pipeline line 1115.

Also, on the previous step all quantiles are equal to 0.0 for some reason.
Can you help me?

**Comment by owenjm** [comment]
Hi,

Sorry you've been having issues with the pipeline.  Yes, the Spearman's correlation isn't going to work if the quantiles are all 0 -- that would mean that no reads have been mapped, something which definitely shouldn't happen.  (Looks like I should add a sanity check in the code so it doesn't die so horribly -- sorry about that!)

If you can email me directly and attach your pipeline log file I can try to work out what's gone wrong.  But some basic things to check first off: did you have reads aligning at the bowtie2 stage?  If so, can you see reads in the generated BAM files if you look at them in IGV?

Cheers,
Owen

**Comment by foriin** [comment]
Thanks for replying!
Yeah, I've searched for your email, but couldn't find it :( 
Bowtie2 seems to work correctly, I got two *-ext300.bam files
If you don't want to show here your email, here's mine: ilyin@img.ras.ru
Nope, I can't view them in IGV, it says "Could not load index file for: /home/user/DamID_owenjm/RUN/Dam1-ext300.bam An index file is required for SAM & BAM files."
