### ISSUE TITLE
Option to specify the Dam-only VS Dam-fusion files

### ISSUE THREAD

**Issue by ademcan** [owenjm/damidseq_pipeline#3]
[Enhancement]
I think it would be really nice to have the options to identidy the Dam-fusion and the Dam-only bam files directly from the command line, for examples --dam --fusion. So far, the tool can distinguish them if the word "Dam" is in the filename, which means that one needs to change the bam file names accordingly. I am used to keep the sample names with the .bam extension as filenames, it's easier for looping in bash :)
Thank you again for this tool.
My 2 cents.

**Comment by owenjm** [comment]
Hi,
Thanks for the feedback , and that's a good suggestion; I'll try to implement it in the next build.
Cheers,
Owen

**Comment by owenjm** [comment]
Please try version 1.2.5 that I've just committed.  I've added in two new options:

--dam  allows you specify the dam-only control file
--out_name  allows you to customise [protein] in the "[protein]-vs-Dam" output file name

(You do not need to specify --out_name if using --dam, but it may be useful, or it can be used independently of --dam.  Of course neither option needs to be specified, in which case the script will assign the dam control as before.)

Cheers,
Owen

**Comment by ademcan** [comment]
Hi,
Thank you for the quick implementation, it is very nice of you :)
I will definitely give it a try.
Thanks
